#!/bin/bash
# run_sparseclone.sh — Docker-local SSH wrapper
# Auto-generated by SparseClone Manager on 2026-03-23T13:37:26.225Z
# Executes exadata_sparseclone_create_v6.sh on the target Exadata via SSH.

set -euo pipefail

# Parse extra flags (--refresh etc.) — --config consumed; remote path is baked in
EXTRA_FLAGS=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --config) shift 2 ;;
    *)        EXTRA_FLAGS="$EXTRA_FLAGS $1"; shift ;;
  esac
done

SSH_TARGET="oracle@10.242.81.239"
REMOTE_SCRIPT="/home/oracle/scripts/logs/exadata_sparseclone_create_v6.sh"
REMOTE_CONFIG="/home/oracle/scripts/logs/sparse_clone.conf"
SSH_BIN="$(command -v ssh || echo /usr/bin/ssh)"

CONF_FLAGS=""

echo "[INFO] SSH target   : $SSH_TARGET"
echo "[INFO] Remote script: $REMOTE_SCRIPT"
echo "[INFO] Remote config: $REMOTE_CONFIG"
[[ -n "$EXTRA_FLAGS" ]] && echo "[INFO] Extra flags  : $EXTRA_FLAGS"
echo "[CMD] ssh -o StrictHostKeyChecking=no -o ConnectTimeout=15 -o BatchMode=yes -o LogLevel=ERROR -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -o KexAlgorithms=ecdh-sha2-nistp256,curve25519-sha256,diffie-hellman-group14-sha256 -i "id_rsa" -tt $SSH_TARGET /bin/bash $REMOTE_SCRIPT --config $REMOTE_CONFIG $CONF_FLAGS$EXTRA_FLAGS"

exec "$SSH_BIN" -o StrictHostKeyChecking=no -o ConnectTimeout=15 -o BatchMode=yes -o LogLevel=ERROR -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -o KexAlgorithms=ecdh-sha2-nistp256,curve25519-sha256,diffie-hellman-group14-sha256 -i "id_rsa" -tt "$SSH_TARGET" /bin/bash "$REMOTE_SCRIPT" --config "$REMOTE_CONFIG" $CONF_FLAGS$EXTRA_FLAGS